FROM debian:stable

# Environment variable for ppm-daemon to find its configuration file
ENV PPM_CONFIG=/app/data/service.yml

RUN apt-get update && apt-get install -y curl && apt-get clean

RUN curl https://www.gremory.org/gitea/api/packages/fargie_s/debian/repository.key -o /etc/apt/keyrings/gitea-fargie_s.asc
RUN echo "deb [signed-by=/etc/apt/keyrings/gitea-fargie_s.asc] https://www.gremory.org/gitea/api/packages/fargie_s/debian trixie main" | tee -a /etc/apt/sources.list.d/gitea.list

RUN apt-get update && \
    apt-get install -y partner-pm && \
    apt-get autoremove && apt-get clean

COPY . /app
WORKDIR /app

ENTRYPOINT [ "/usr/bin/ppm-daemon" ]
