name: test

on: [workflow_dispatch, push]

env:
  CARGO_TERM_COLOR: never
  RUST_LOG_STYLE: never
  RUST_LOG: trace

jobs:
  build-ubuntu-default:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5
      - name: Build project
        run: cargo build
      - name: Run tests
        run: cargo test
      - name: Run clippy
        run: cargo clippy -- -D warnings

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Fetch sources
        uses: actions/checkout@v5
      - name: Build project
        run: cargo build
      - name: Run tests
        run: cargo test -- --no-capture
      - name: Run clippy
        run: cargo clippy -- -D warnings

  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Generate ChangeLog
        uses: docker://alpine:latest
        env:
          RUST_LOG: warn
        with:
          args: |
            /bin/sh -c "printf '[safe]\ndirectory = *\n' > /etc/gitconfig && apk add git-cliff && git-cliff -u && echo Ok"
