name: release
on:
  push:
    tags:
      - "v[0-9]*.[0-9]*.[0-9]*"

jobs:
  github_build:
    name: Build release binaries
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            name: partner-pm-linux-amd64.tar.gz
            arch: x86_64

          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            name: partner-pm-linux-arm64.tar.gz
            arch: aarch64

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(?<version>.*)"
      # Cache files between builds
      - name: Setup | Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          override: true
          profile: minimal
          target: ${{ matrix.target }}

      - name: Build | Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path Cargo.toml --release --target ${{ matrix.target }} --config 'package.version="${{ steps.tagName.outputs.version }}"'
          use-cross: ${{ matrix.os == 'ubuntu-latest' }}

      - name: Prepare artifacts
        run: |
          cd target/${{ matrix.target }}/release
          # TODO: investigate better cross platform stripping
          strip ppm ppm-daemon ppm-launcher || true
          tar czvf ../../../${{ matrix.name }} ppm ppm-daemon ppm-launcher
          cd -

      - name: Test Bin
        if: matrix.arch == 'x86_64'
        run: |
          cd target/${{ matrix.target }}/release
          ./ppm --version
          cd -

      - name: Deploy | Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}
          path: ${{ matrix.name }}

  github_release:
    name: Create GitHub Release
    needs: github_build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup | Artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-dist

      - name: Setup | Checksums
        run: |
          ls -lha release-dist
          for file in release-dist/**/*; do openssl dgst -sha256 -r "$file" | awk '{print $1}' > "${file}.sha256"; done

      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: release-dist/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
